version: 2

updates:
  - package-ecosystem: bundler
    directory: /api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
