max_retries: 12 # About < 12 hours. Ref: https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry

:queues:
  - default
  - mailers

:schedule:
  PurgeUnattachedUploadsJob:
    every: 6h
