version: '3.9'

volumes:
  postgres:
  redis:
  minio:

services:
  varnish:
    build: docker/varnish

    tmpfs:
      - /var/lib/varnish:exec

    depends_on:
      - rails
      - minio

  rails: &rails
    build:
      context: .

      args:
        - OPENID_CLIENT_ID=
        - OPENID_CONFIGURATION_ENDPOINT=

    environment:
      - DATABASE_URL=postgresql://postgres@postgres/mssform
      - MEMCACHE_SERVERS=memcached
      - MINIO_ACCESS_KEY_ID=mssform
      - MINIO_BUCKET=uploads
      - MINIO_ENDPOINT=
      - MINIO_SECRET_ACCESS_KEY=
      - REDIS_URL=redis://redis
      - SUBMISSION_MAIL_CC='DDBJ Mass Submission System (MSS) <mass@ddbj.nig.ac.jp>'

    depends_on:
      - postgres
      - redis
      - memcached
      - minio

  sidekiq:
    <<: *rails
    command: ["bundle", "exec", "sidekiq"]

  postgres:
    image: postgres:14

    environment:
      - POSTGRES_DB=mssform
      - POSTGRES_HOST_AUTH_METHOD=trust

    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6
    command: ["--appendonly", "yes"]

    volumes:
      - redis:/data

  memcached:
    image: memcached:latest

  minio:
    image: minio/minio:latest
    command: ["server", "/data", "--console-address", ":9001"]

    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=

    volumes:
      - minio:/data
