services:
  varnish:
    ports:
      - 3000:80

  rails:
    environment:
      - MINIO_ENDPOINT=http://mssform.localhost:3000
      - MINIO_SECRET_ACCESS_KEY=changeme

    extra_hosts:
      - mssform.localhost:host-gateway

  minio:
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
