source 'https://rubygems.org'

ruby file: '.ruby-version'

gem 'rails', '~> 7.1.3'

gem 'aws-sdk-s3'
gem 'dalli'
gem 'enumerize'
gem 'exception_notification'
gem 'google-apis-sheets_v4'
gem 'googleauth'
gem 'http'
gem 'jb'
gem 'jwt'
gem 'mail', '~> 2.8.1' # https://github.com/mikel/mail/issues/1489
gem 'pg'
gem 'puma'
gem 'rubyzip', require: 'zip'
gem 'sidekiq'
gem 'sidekiq-scheduler', '>= 5.0.0.beta2'

group :test do
  gem 'climate_control'
  gem 'email_spec'
  gem 'factory_bot_rails', group: :development
  gem 'rspec-default_http_header'
  gem 'rspec-rails', group: :development
  gem 'webmock'
end
