source 'https://rubygems.org'

ruby '3.1.1'

gem 'rails', '~> 7.0.0'

gem 'aws-sdk-s3'
gem 'dalli'
gem 'enumerize'
gem 'google-apis-sheets_v4'
gem 'googleauth'
gem 'http'
gem 'jb'
gem 'jwt'
gem 'mail'
gem 'pg'
gem 'puma'
gem 'sidekiq'

group :development do
  gem 'debug', group: :test
end

group :test do
  gem 'climate_control'
  gem 'factory_bot_rails', group: :development
  gem 'rspec-rails',       group: :development
  gem 'webmock'
end
