development:
  app_url:                http://mssform.localhost:3000
  extracts_dir:           <%= Rails.root.join("storage/extracts") %>
  mass_dir_path_template: <%= Rails.root.join("storage/mass/{user}") %>
  submissions_dir:        <%= Rails.root.join("storage/submissions") %>
  web_url:                http://mssform.localhost:4200

test:
  app_url:                http://mssform.example.com:3000
  extracts_dir:           <%= Rails.root.join("tmp/storage/extracts") %>
  mass_dir_path_template: <%= Rails.root.join("tmp/storage/mass/{user}") %>
  submissions_dir:        <%= Rails.root.join("tmp/storage/submissions") %>
  web_url:                http://mssform.example.com:4200

production: &production
  app_url:                https://mss.ddbj.nig.ac.jp
  extracts_dir:           <%= Rails.root.join("storage/extracts") %>
  mass_dir_path_template: /submission/{user}/submission/{user}/mass
  sentry_dsn:             https://d0a88749c20cf46d63f4bb1028e427dc@o4506770361024512.ingest.sentry.io/4506770364891136
  submissions_dir:        <%= Rails.root.join("storage/submissions") %>
  web_url:                https://mss.ddbj.nig.ac.jp

staging:
  <<: *production
  app_url:              https://mss-staging.ddbj.nig.ac.jp
  mail_allowed_domains: ddbj.nig.ac.jp,ursm.jp
  web_url:              https://mss-staging.ddbj.nig.ac.jp
