default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mssform_development

test:
  <<: *default
  database: mssform_test

production: &production
  primary:
    <<: *default
    url: <%= Rails.application.credentials.database_url %>
    database: mssform

  queue:
    <<: *default
    url: <%= Rails.application.credentials.database_url %>
    database: mssform_queue
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    url: <%= Rails.application.credentials.database_url %>
    database: mssform_cache
    migrations_paths: db/cache_migrate

staging:
  <<: *production
