service: mssform
image: w3const/mssform
require_destination: true

registry:
  username: w3const

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

  args:
    APP_GID: 11370
    APP_UID: 2233

env:
  clear:
    SOLID_QUEUE_IN_PUMA: true
    TZ:                  Asia/Tokyo

  secret:
    - RAILS_MASTER_KEY

volumes:
  - /mnt/submission:/submission

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

ssh:
  user: w3const

accessories:
  postgres:
    image: postgres:17.4

    options:
      user: 2233:11370

    env:
      secret:
        - POSTGRES_PASSWORD

      clear:
        POSTGRES_DB: mssform
        TZ:          Asia/Tokyo

  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    cmd: server /data

    proxy:
      app_port: 9000

      healthcheck:
        path: /minio/health/live

    options:
      user: 2233:11370

    env:
      secret:
        - MINIO_ROOT_USER
        - MINIO_ROOT_PASSWORD

      clear:
        TZ: Asia/Tokyo
