servers:
  web:
    hosts:
      - mssform-production

    options:
      group-add: 60000 # submitter

proxy:
  host: mss.ddbj.nig.ac.jp

volumes:
  - /mnt/submission:/submission
  - /lustre9/open/home/w3dfast/ggs_volumes:/lustre9/open/home/w3dfast/ggs_volumes:ro
  - ./volumes/mssform-production/storage:/rails/storage

accessories:
  postgres:
    host: mssform-production

    volumes:
      - ./volumes/mssform-production/postgres:/var/lib/postgresql/data

  seaweedfs:
    host: mssform-production

    proxy:
      host: mss-storage.ddbj.nig.ac.jp

    volumes:
      - ./volumes/mssform-production/seaweedfs:/data
