servers:
  web:
    - mssform-production

proxy:
  host: mss.ddbj.nig.ac.jp

builder:
  args:
    API_URL: https://mss.ddbj.nig.ac.jp/api

volumes:
  - ./volumes/mssform-production/storage:/rails/storage

accessories:
  postgres:
    host: mssform-production

    volumes:
      - ./volumes/mssform-production/postgres:/var/lib/postgresql/data

  minio:
    host: mssform-production

    proxy:
      host: mss-storage.ddbj.nig.ac.jp

    volumes:
      - ./volumes/mssform-production/minio:/data
