service: mssform
image: w3const/mssform
require_destination: true

registry:
  username: w3const

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

  args:
    APP_GID: 11370
    APP_UID: 2233

env:
  clear:
    SOLID_QUEUE_IN_PUMA: true
    TZ:                  Asia/Tokyo

  secret:
    - RAILS_MASTER_KEY

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

ssh:
  user: w3const

accessories:
  postgres:
    image: postgres:17.4

    options:
      user: 2233:11370

    env:
      secret:
        - POSTGRES_PASSWORD

      clear:
        POSTGRES_DB: mssform
        TZ:          Asia/Tokyo

  garage:
    image: w3const/mssform-garage

    proxy:
      app_port: 3900

      healthcheck:
        interval: 3
        path: /health
        port: 3903

    options:
      user: 2233:11370

    files:
      - docker/garage/garage.production.toml.erb:/etc/garage.toml

    env:
      secret:
        - GARAGE_API_KEY
        - GARAGE_SECRET_KEY

      clear:
        GARAGE_BUCKET_NAME: uploads
        GARAGE_KEY_NAME:    mssform
        TZ:                 Asia/Tokyo
