servers:
  web:
    - mssform-staging

proxy:
  host: mss-staging.ddbj.nig.ac.jp

builder:
  args:
    API_URL: https://mss-staging.ddbj.nig.ac.jp/api

env:
  clear:
    RAILS_ENV: staging

volumes:
  - ./volumes/mssform-staging/storage:/rails/storage

accessories:
  postgres:
    host: mssform-staging

    volumes:
      - ./volumes/mssform-staging/postgres:/var/lib/postgresql/data

  minio:
    host: mssform-staging

    proxy:
      host: mss-storage-staging.ddbj.nig.ac.jp

    volumes:
      - ./volumes/mssform-staging/minio:/data
