servers:
  web:
    hosts:
      - mssform-staging

    options:
      group-add: 61000 # ts-submitter

proxy:
  host: mss-staging.ddbj.nig.ac.jp

builder:
  args:
    RAILS_ENV: staging

env:
  clear:
    RAILS_ENV: staging

volumes:
  - /mnt/submission:/submission
  - ./volumes/mssform-staging/storage:/rails/storage

accessories:
  postgres:
    host: mssform-staging

    volumes:
      - ./volumes/mssform-staging/postgres:/var/lib/postgresql/data

  minio:
    host: mssform-staging

    proxy:
      host: mss-storage-staging.ddbj.nig.ac.jp

    volumes:
      - ./volumes/mssform-staging/minio:/data
