locales:
  - key: ja
    label:
      en: Japanese
      ja: 日本語

  - key: en
    label:
      en: English
      ja: 英語

data_types:
  - key: wgs
    label: 'WGS: Whole Genome Shotgun'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/wgs-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/wgs.html

  - key: gnm
    label: 'GNM: Finished Level Genome sequence, non-WGS'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/genome-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/genome.html

  - key: mag
    label: 'MAG: Metagenome-Assembled Genome'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/metagenome-assembly-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/metagenome-assembly.html

  - key: sag
    label: 'SAG: Single Amplified Genome'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/single-amplified-genome-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/single-amplified-genome.html

  - key: tls
    label: 'TLS: Targeted Locus Study'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/tls-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/tls.html

  - key: htg
    label: 'HTG: High Throughput Genomic Sequences'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/htg-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/htg.html

  - key: tsa
    label: 'TSA: Transcriptome Shotgun Assembly'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/tsa-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/tsa.html

  - key: htc
    label: 'HTC: High Throughput cDNA Sequences'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/htc-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/htc.html

  - key: est
    label: 'EST: Expressed Sequence Tags'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/est-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/est.html

  - key: misc
    label: 'MISC: Sequences that are not included in above types'
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/submission-e.html
      ja: https://www.ddbj.nig.ac.jp/submission.html

  - key: ask
    label: Ask DDBJ curator to judge a correct datatype
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/submission-e.html
      ja: https://www.ddbj.nig.ac.jp/submission.html

sequencers:
  - key: ngs
    label: NGS

  - key: sanger
    label: Sanger dideoxy sequencing
