data_types:
  - key: wgs
    label: draft genome (WGS)
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/wgs-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/wgs.html

  - key: complete_genome
    label: complete or nearly complete genome
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/genome-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/genome.html

  - key: mag
    label: Metagenome-Assembled Genome (MAG)
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/metagenome-assembly-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/metagenome-assembly.html

  - key: sag
    label: Single amplified genome (SAG)
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/single-amplified-genome-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/single-amplified-genome.html

  - key: tls
    label: TLS
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/tls-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/tls.html

  - key: htg
    label: HTG
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/htg-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/htg.html

  - key: tsa
    label: TSA
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/tsa-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/tsa.html

  - key: htc
    label: full length cDNA (HTC)
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/htc-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/htc.html

  - key: est
    label: EST
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/ddbj/est-e.html
      ja: https://www.ddbj.nig.ac.jp/ddbj/est.html

  - key: dna
    label: Gene sequences (DNA)
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/submission-e.html
      ja: https://www.ddbj.nig.ac.jp/submission.html

  - key: rna
    label: Gene sequences (RNA)
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/submission-e.html
      ja: https://www.ddbj.nig.ac.jp/submission.html

  - key: ask
    label: Ask DDBJ curator to judge a correct datatype
    ddbj_page_url:
      en: https://www.ddbj.nig.ac.jp/submission-e.html
      ja: https://www.ddbj.nig.ac.jp/submission.html

sequencers:
  - key: ngs
    label: NGS

  - key: sanger
    label: Sanger dideoxy sequencing
