development:
  endpoint:   http://localhost:8333
  bucket:     mssform
  access_key: <%= ENV['SEAWEEDFS_ACCESS_KEY'] %>
  secret_key: <%= ENV['SEAWEEDFS_SECRET_KEY'] %>

production: &production
  endpoint:   https://mss-storage.ddbj.nig.ac.jp
  bucket:     uploads
  access_key: <%= Rails.application.credentials.dig(:seaweedfs, :access_key) %>
  secret_key: <%= Rails.application.credentials.dig(:seaweedfs, :secret_key) %>

staging:
  <<: *production
  endpoint: https://mss-storage-staging.ddbj.nig.ac.jp
