<% if Rails.env.test? %>
test:
  service: Disk
  root:    <%= Rails.root.join('tmp/storage') %>
<% else %>
seaweedfs:
  service:           S3
  endpoint:          <%= Rails.application.config_for(:seaweedfs).endpoint %>
  force_path_style:  true
  bucket:            uploads
  access_key_id:     '<%= Rails.application.config_for(:seaweedfs).access_key %>'
  secret_access_key: '<%= Rails.application.config_for(:seaweedfs).secret_key %>'
  region:            us-east-1
<% end %>
