<% if Rails.env.test? %>
test:
  service: Disk
  root:    <%= Rails.root.join('tmp/storage') %>
<% else %>
minio:
  service:           S3
  endpoint:          <%= Rails.application.config_for(:minio).endpoint %>
  force_path_style:  true
  bucket:            uploads
  access_key_id:     <%= Rails.application.config_for(:minio).access_key_id %>
  secret_access_key: <%= Rails.application.config_for(:minio).secret_access_key %>
  region:            not-applicable
<% end %>
