<% if Rails.env.test? %>
test:
  service: Disk
  root:    <%= Rails.root.join('tmp/storage') %>
<% else %>
minio:
  service:           S3
  endpoint:          <%= ENV.fetch('MINIO_ENDPOINT') %>
  force_path_style:  true
  bucket:            uploads
  access_key_id:     <%= ENV.fetch('MINIO_ACCESS_KEY_ID') %>
  secret_access_key: <%= ENV.fetch('MINIO_SECRET_ACCESS_KEY') %>
  region:            not-applicable
<% end %>
