#!/bin/bash

set -e

export STAGE=${0##*/}

dir=${0%/*}

export COMPOSE_FILE=$dir/base.yml:$dir/$STAGE.yml
export COMPOSE_PROJECT_NAME=mssform-$STAGE

set -o allexport
source $dir/$STAGE.env
set +o allexport

exec docker compose $@
