#!/bin/bash

set -e

export STAGE=${0##*/}

dir=${0%/*}

export COMPOSE_FILE=$dir/base.yml:$dir/$STAGE.yml
export COMPOSE_PROJECT_NAME=mssform-$STAGE
export DOCKER_BUILDKIT=1

export NODE_VERSION=$(cat $dir/../frontend/.node-version)
export RUBY_VERSION=$(cat $dir/../backend/.ruby-version)

set -o allexport
source $dir/$STAGE.env
set +o allexport

exec docker compose $@
