services:
  varnish:
    build: ../docker/varnish
    user: root # https://github.com/varnish/docker-varnish/issues/53

    environment:
      VARNISH_HTTP_PORT: 8080

    ports:
      - ${VARNISH_PORT:?}:8080

    tmpfs:
      - /var/lib/varnish/varnishd:exec

    depends_on:
      rails:
        condition: service_started

  rails: &rails
    build:
      context: ..

      args:
        APP_GID:
        APP_UID:
        MASS_DIR_PATH_TEMPLATE:
        NODE_VERSION:
        OPENID_CLIENT_ID:
        OPENID_CONFIGURATION_ENDPOINT:
        RUBY_VERSION:

    init: true

    environment:
      CURATOR_ML_ADDRESS:          '"DDBJ Mass Submission System (MSS)" <mass@ddbj.nig.ac.jp>'
      DATABASE_URL:
      EXTRACTION_WORKDIR:          /app/work/extraction
      FORCE_SSL:
      GOOGLE_ACCOUNT_TYPE:         service_account
      GOOGLE_CLIENT_EMAIL:
      GOOGLE_CLIENT_ID:
      GOOGLE_PRIVATE_KEY:
      IRB_USE_AUTOCOMPLETE:        'false'
      MAIL_ALLOWED_DOMAINS:
      MASS_DIR_PATH_TEMPLATE:
      MEMCACHE_SERVERS:            memcached
      MINIO_ACCESS_KEY_ID:
      MINIO_BUCKET:                uploads
      MINIO_ENDPOINT:
      MINIO_SECRET_ACCESS_KEY:
      MSSFORM_URL:
      MSS_WORKING_LIST_SHEET_ID:
      MSS_WORKING_LIST_SHEET_NAME:
      OPENID_CLIENT_ID:
      SECRET_KEY_BASE:
      SENTRY_CURRENT_ENV:
      SENTRY_DSN:
      SMTP_ADDRESS:
      SMTP_AUTHENTICATION:
      SMTP_DOMAIN:
      SMTP_PASSWORD:
      SMTP_PORT:
      SMTP_USERNAME:
      STAGE:
      SUBMISSIONS_DIR:             /app/submissions

    depends_on:
      memcached:
        condition: service_started

  solid_queue:
    <<: *rails
    command: [bundle, exec, rake, solid_queue:start]

  memcached:
    image: memcached:latest
