services:
  varnish:
    build: varnish
    user: root # https://github.com/varnish/docker-varnish/issues/53

    environment:
      VARNISH_HTTP_PORT: 8080

    ports:
      - ${VARNISH_PORT:?}:8080

    tmpfs:
      - /var/lib/varnish/varnishd:exec

    depends_on:
      rails:
        condition: service_started

  rails:
    build:
      context: ../
      dockerfile: api/Dockerfile

      args:
        API_URL:
        APP_GID:
        APP_UID:
        MASS_DIR_PATH_TEMPLATE:
        NODE_VERSION:
        RUBY_VERSION:

    init: true

    environment:
      CURATOR_ML_ADDRESS:          '"DDBJ Mass Submission System (MSS)" <mass@ddbj.nig.ac.jp>'
      DATABASE_URL:
      DISABLE_SSL:
      EXTRACTION_WORKDIR:          /app/work/extraction
      GOOGLE_ACCOUNT_TYPE:         service_account
      GOOGLE_CLIENT_EMAIL:
      GOOGLE_CLIENT_ID:
      GOOGLE_PRIVATE_KEY:
      MAIL_ALLOWED_DOMAINS:
      MASS_DIR_PATH_TEMPLATE:
      MINIO_ACCESS_KEY_ID:
      MINIO_BUCKET:                uploads
      MINIO_ENDPOINT:
      MINIO_SECRET_ACCESS_KEY:
      MSSFORM_URL:
      MSS_WORKING_LIST_SHEET_ID:
      MSS_WORKING_LIST_SHEET_NAME:
      OIDC_CLIENT_ID:
      OIDC_ISSUER_URL:
      SECRET_KEY_BASE:
      SENTRY_CURRENT_ENV:
      SENTRY_DSN:
      SMTP_ADDRESS:
      SMTP_AUTHENTICATION:
      SMTP_DOMAIN:
      SMTP_PASSWORD:
      SMTP_PORT:
      SMTP_USERNAME:
      SOLID_QUEUE_IN_PUMA:         'true'
      STAGE:
      SUBMISSIONS_DIR:             /app/submissions
      WEB_URL:
