volumes:
  mass:
  submissions:
  work:

services:
  rails: &rails-local
    build:
      extra_hosts:
        - keycloak:${HOST_GATEWAY_IP:-172.17.0.1}

    environment:
      DISABLE_SSL: 'true'

    extra_hosts:
      - host.docker.internal:host-gateway
      - keycloak:host-gateway
      - mssform.localhost:host-gateway

    volumes:
      - mass:/submission/keycloak/submissions/keycloak/mass
      - submissions:/app/submissions
      - work:/app/work

    depends_on:
      - mailhog

  solid_queue:
    <<: *rails-local

  mailhog:
    image: mailhog/mailhog

    ports:
      - 8025:8025
