volumes:
  mass:
  submissions:
  work:

services:
  rails: &rails-local
    build:
      extra_hosts:
        - keycloak:${HOST_GATEWAY_IP:-172.17.0.1}

    environment:
      DISABLE_SSL: 'true'
      DATABASE_URL: postgres://postgres@postgres/mssform

    extra_hosts:
      - host.docker.internal:host-gateway
      - keycloak:host-gateway
      - mssform.localhost:host-gateway

    volumes:
      - mass:/submission/keycloak/submissions/keycloak/mass
      - submissions:/app/submissions
      - work:/app/work

    depends_on:
      - postgres
      - minio
      - mailhog

  solid_queue:
    <<: *rails-local

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: mssform
      POSTGRES_HOST_AUTH_METHOD: trust

  minio:
    image: minio/minio
    command: [server, /data]

  mailhog:
    image: mailhog/mailhog

    ports:
      - 8025:8025
