volumes:
  work:
  postgres:
  minio:

services:
  rails: &rails-local
    extra_hosts:
      - mssform.localhost:host-gateway

    volumes:
      - ../api/tmp/submission:/submission
      - ../api/tmp/submissions:/app/submissions
      - work:/app/work

    depends_on:
      - postgres
      - minio
      - mailhog

  solid_queue:
    <<: *rails-local

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: mssform
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: [server, /data]

    volumes:
      - minio:/data

  mailhog:
    image: mailhog/mailhog

    ports:
      - 8025:8025
