services:
  varnish:
    ports:
      - 4200:80

  rails: &rails-local
    build:
      extra_hosts:
        - keycloak.localhost:172.17.0.1

    extra_hosts:
      - keycloak.localhost:host-gateway
      - mssform.localhost:host-gateway

    volumes:
      - type: bind
        source: ../submissions
        target: /app/submissions

    depends_on:
      - mailhog

  sidekiq:
    <<: *rails-local

  minio:
    ports:
      - 9000:9000
      - 9001:9001

  mailhog:
    image: mailhog/mailhog

    ports:
      - 8025:8025
