volumes:
  work:
  postgres:
  minio:

services:
  rails:
    extra_hosts:
      - mssform.localhost:host-gateway

    volumes:
      - ../api/tmp/submission:/submission
      - ../api/tmp/submissions:/app/submissions
      - work:/app/work

    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      mailhog:
        condition: service_started

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: mssform
      POSTGRES_HOST_AUTH_METHOD: trust

    volumes:
      - postgres:/var/lib/postgresql/data

    healthcheck:
      test: [CMD-SHELL, pg_isready]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    command: [server, /data]

    volumes:
      - minio:/data

  mailhog:
    image: mailhog/mailhog

    ports:
      - 8025:8025
