volumes:
  submissions:

services:
  rails: &rails-local
    build:
      extra_hosts:
        - keycloak:${HOST_GATEWAY_IP:-172.17.0.1}

    extra_hosts:
      - keycloak:host-gateway
      - mssform.localhost:host-gateway

    volumes:
      - submissions:/app/submissions

    depends_on:
      - mailhog

  sidekiq:
    <<: *rails-local

  minio:
    ports:
      - 9000:9000
      - 9001:9001

  mailhog:
    image: mailhog/mailhog

    ports:
      - 8025:8025
