services:
  rails: &rails
    group_add:
      - '60000' # submitter

    volumes:
      - type: bind
        source: ~/submissions/$STAGE
        target: /app/submissions
      - type: bind
        source: /submission
        target: /submission
      - type: bind
        source: ~/mssform/work/$STAGE
        target: /app/work

  solid_queue:
    <<: *rails

  postgres:
    volumes:
      - type: bind
        source: ~/mssform/data/$STAGE/postgres
        target: /var/lib/postgresql/data

  minio:
    volumes:
      - type: bind
        source: ~/mssform/data/$STAGE/minio
        target: /data
