services:
  rails: &rails
    group_add:
      - '60000' # submitter

    volumes:
      - type: bind
        source: ~/submissions/$STAGE
        target: /app/submissions
      - type: bind
        source: /submission
        target: /submission
      - type: bind
        source: ~/mssform/work/$STAGE
        target: /app/work

    restart: unless-stopped

  solid_queue:
    <<: *rails

networks:
  default:
    external: true
    name: mssform-$STAGE
