services:
  rails: &rails
    volumes:
      - type: bind
        source: ~/submissions/$STAGE
        target: /app/submissions

  sidekiq:
    <<: *rails

  postgres:
    volumes:
      - type: bind
        source: ~/mssform/data/$STAGE/postgres
        target: /var/lib/postgresql/data

  redis:
    volumes:
      - type: bind
        source: ~/mssform/data/$STAGE/redis
        target: /data

  minio:
    volumes:
      - type: bind
        source: ~/mssform/data/$STAGE/minio
        target: /data
