services:
  varnish:
    restart: unless-stopped

    ports:
      - 3101:80

  rails: &rails-staging
    restart: unless-stopped

    volumes:
      - $DATA_DIR/submissions:/app/submissions

  sidekiq:
    <<: *rails-staging

  postgres:
    restart: unless-stopped

    volumes:
      - $DATA_DIR/postgres:/var/lib/postgresql/data

  redis:
    restart: unless-stopped

    volumes:
      - $DATA_DIR/redis:/data

  memcached:
    restart: unless-stopped

  minio:
    restart: unless-stopped

    volumes:
      - $DATA_DIR/minio:/data
