services:
  varnish:
    restart: unless-stopped

  rails: &rails
    restart: unless-stopped

    volumes:
      - type: bind
        source: ~/submissions/$STAGE
        target: /app/submissions

  sidekiq:
    <<: *rails

  postgres:
    restart: unless-stopped

    volumes:
      - type: bind
        source: ~/data/$STAGE/postgres
        target: /var/lib/postgresql/data

  redis:
    restart: unless-stopped

    volumes:
      - type: bind
        source: ~/data/$STAGE/redis
        target: /data

  memcached:
    restart: unless-stopped

  minio:
    restart: unless-stopped

    volumes:
      - type: bind
        source: ~/data/$STAGE/minio
        target: /data
