/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get current user information. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the current user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            uid: string;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a list of submissions. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the list of submissions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submissions: components["schemas"]["Submission"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** @description Create a new submission. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        submission: {
                            tpa: boolean;
                            /** @enum {string} */
                            upload_via: "webui" | "dfast" | "mass_directory";
                            files?: string[];
                            /** @description Extraction ID (for dfast or mass_directory upload) */
                            extraction_id?: number;
                            entries_count: number;
                            /** Format: date */
                            hold_date?: string | null;
                            sequencer: string;
                            data_type: string;
                            description?: string | null;
                            email_language: string;
                            contact_person: {
                                email: string;
                                full_name: string;
                                affiliation: string;
                            };
                            other_people: {
                                email: string;
                                full_name: string;
                            }[];
                        };
                    };
                };
            };
            responses: {
                /** @description Returns the created submission. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submission: {
                                id: string;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/last_submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the last submitted submission for pre-filling form fields. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the last submitted submission. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submission: {
                                id: string;
                                contact_person: {
                                    id: number;
                                    email: string;
                                    full_name: string;
                                    affiliation: string;
                                };
                                other_people: {
                                    id: number;
                                    email: string;
                                    full_name: string;
                                }[];
                                sequencer: string;
                                email_language: string;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{mass_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a submission. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mass_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the requested submission. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submission: components["schemas"]["Submission"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{mass_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add an upload to an existing submission. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mass_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        upload: {
                            /** @enum {string} */
                            via: "webui" | "dfast" | "mass_directory";
                            files?: string[];
                            /** @description Extraction ID (for dfast or mass_directory upload) */
                            extraction_id?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Upload accepted. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dfast_extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a DFAST extraction. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        ids: string[];
                    };
                };
            };
            responses: {
                /** @description Returns the created extraction. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DfastExtraction"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                422: components["responses"]["UnprocessableContent"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dfast_extractions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a DFAST extraction. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the requested extraction. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DfastExtraction"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mass_directory_extractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a mass directory extraction. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the created extraction. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MassDirectoryExtraction"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mass_directory_extractions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a mass directory extraction. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns the requested extraction. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MassDirectoryExtraction"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Submission: {
            id: string;
            /** Format: date-time */
            created_at: string;
            status: string | null;
            accessions: string[];
            uploads: components["schemas"]["Upload"][];
        };
        Upload: {
            id: number;
            /** Format: date-time */
            created_at: string;
            files: string[];
            dfast_job_ids: string[];
        };
        DfastExtraction: {
            /** Format: uri */
            _self: string;
            id: number;
            state: components["schemas"]["ExtractionState"];
            error: {
                id: string;
                job_id?: string;
                reason?: string;
            } | null;
            files: components["schemas"]["DfastExtractionFile"][];
        };
        MassDirectoryExtraction: {
            /** Format: uri */
            _self: string;
            id: number;
            state: components["schemas"]["ExtractionState"];
            error: {
                id: string;
                job_id?: string;
                reason?: string;
            } | null;
            files: components["schemas"]["MassDirectoryExtractionFile"][];
        };
        /** @enum {string} */
        ExtractionState: "pending" | "fulfilled" | "rejected";
        DfastExtractionFile: {
            name: string;
            basename: string;
            size: number;
            isParsing: boolean;
            parsedData: components["schemas"]["ParsedData"] | null;
            isParseSucceeded: boolean;
            errors: components["schemas"]["ExtractionFileError"][] | null;
            isAnnotation: boolean;
            isSequence: boolean;
            jobId: string;
        };
        MassDirectoryExtractionFile: {
            name: string;
            basename: string;
            size: number;
            isParsing: boolean;
            parsedData: components["schemas"]["ParsedData"] | null;
            isParseSucceeded: boolean;
            errors: components["schemas"]["ExtractionFileError"][] | null;
            isAnnotation: boolean;
            isSequence: boolean;
        };
        ParsedData: {
            contactPerson?: {
                fullName: string;
                email: string;
                affiliation: string;
            };
            holdDate?: string | null;
            entriesCount?: number;
        };
        ExtractionFileError: {
            id: string;
            value?: string | null;
        };
    };
    responses: {
        /** @description Not authenticated. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Does not have access rights to the resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description The requested resource could not be found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid parameter or payload was specified. */
        UnprocessableContent: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
