default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: mssform_development

  cache:
    <<: *default
    database: mssform_cache_development
    migrations_paths: db/cache_migrate

test:
  primary:
    <<: *default
    database: mssform_test

  cache:
    <<: *default
    database: mssform_cache_development
    migrations_paths: db/cache_migrate

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: mssform

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: mssform_queue
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: mssform_cache
    migrations_paths: db/cache_migrate
