- hosts: all

  tasks:
    - git:
        repo: https://github.com/ddbj/w3const_base.git
        dest: ~/w3const_base

    - cron:
        name: healthcheck-mssform-{{ item }}
        minute: '*/10'
        job: 'cd /home/w3const/mssform/deploy && ansible/healthcheck {{ item }} > /dev/null'
      loop:
        - staging
        - production
