#!/bin/sh

set -o errexit

if [ $# -ne 1 ]; then
  echo "Usage: $(basename "$0") <staging|production>" 1>&2
  exit 1
fi

compose/"$1" ps --all --format json | jq --raw-output 'select(.State == "exited") | select(.ExitCode != 0) | .Service'
