source "https://rubygems.org"

ruby file: ".ruby-version"

gem "rails", "~> 7.2.1"

gem "aws-sdk-s3"
gem "bootsnap", require: false
gem "dalli"
gem "enumerize"
gem "fetch-api"
gem "google-apis-sheets_v4"
gem "googleauth"
gem "http"
gem "jb"
gem "json"
gem "jwt"
gem "pg"
gem "puma"
gem "rubyzip", require: "zip"
gem "sentry-rails"
gem "solid_cache"
gem "solid_queue"

group :development do
  gem "brakeman", require: false
  gem "debug", require: "debug/prelude", group: :test
  gem "rubocop-rails-omakase", require: false
end

group :test do
  gem "climate_control"
  gem "email_spec"
  gem "factory_bot_rails", group: :development
  gem "rspec-default_http_header"
  gem "rspec-rails", group: :development
  gem "webmock"
end
