source 'https://rubygems.org'

ruby file: '.ruby-version'

gem 'rails', '~> 7.2.0'

gem 'aws-sdk-s3'
gem 'dalli'
gem 'enumerize'
gem 'google-apis-sheets_v4'
gem 'googleauth'
gem 'http'
gem 'jb'
gem 'jwt'
gem 'pg'
gem 'puma'
gem 'rubyzip', require: 'zip'
gem 'sentry-rails'
gem 'solid_queue'

group :test do
  gem 'climate_control'
  gem 'email_spec'
  gem 'factory_bot_rails', group: :development
  gem 'rspec-default_http_header'
  gem 'rspec-rails', group: :development
  gem 'webmock'
end
