name: test

on: push

jobs:
  rails:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14

        ports:
          - 5432:5432

        env:
          POSTGRES_DB: mssform_test
          POSTGRES_HOST_AUTH_METHOD: trust

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: api

    env:
      PGHOST: localhost
      PGUSER: postgres
      RAILS_ENV: test
      TZ: Japan

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: api

      - run: ln -s openid-configuration.local.json ../config/openid-configuration.json
      - run: bin/rails db:prepare
      - run: bundle exec rspec

  ember:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version-file: web/.node-version
          cache: pnpm
          cache-dependency-path: web/pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
      - run: ln -s openid-configuration.local.json ../config/openid-configuration.json
      - run: pnpm test
